### ISSUE TITLE
Tower XP v1.3.2

### ISSUE THREAD

**Issue by tapoffers** [MaliciousFiles/EditPlayerData#12]
[14:54:12.035] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at Assets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId (System.String baseId) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at Il2CppAssets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId(String baseId)
   at EditPlayerData.UI.TowerPlayerDataSetting.GetAllUpgrades() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 594
   at EditPlayerData.UI.TowerPlayerDataSetting.GetValue() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 604
   at EditPlayerData.UI.PlayerDataSetting.GetValueDisplay() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 95
   at EditPlayerData.UI.PlayerDataSettingDisplay.SetSetting(PlayerDataSetting setting) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSettingDisplay.cs:line 71
   at EditPlayerData.UI.EditPlayerDataMenu.UpdateVisibleEntries() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 335
   at EditPlayerData.UI.EditPlayerDataMenu.SetPage(Int32 page) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 354
   at EditPlayerData.UI.EditPlayerDataMenu.<OnMenuOpened>b__12_4(Int32 i) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 259
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]_System.Int32(IntPtr , Int32 , Il2CppMethodInfo* )

**Comment by MaliciousFiles** [comment]
I'll take a look at it. I assume this happened when trying to unlock a tower?

**Comment by MaliciousFiles** [comment]
I can't seem to reproduce the issue. Could you please detail what you did that caused this error?

**Comment by tapoffers** [comment]
Clicking tower xp

**Comment by MaliciousFiles** [comment]
As of now, it appears to be working. Feel free to open another issue if not.
