### ISSUE TITLE
[BUG] Tower XP is broken

### ISSUE THREAD

**Issue by SploeCyber** [MaliciousFiles/EditPlayerData#37]
![image](https://github.com/user-attachments/assets/689ca847-d5db-4545-8c9d-82925688cb75)
[11:30:21.775] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[11:30:21.782] [BloonsTD6_Mod_Helper] Registering ModContent for EditPlayerData...
[11:30:43.966] [Il2CppInterop] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at Assets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId (System.String baseId) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at Il2CppAssets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId(String baseId)
   at EditPlayerData.UI.TowerPlayerDataSetting.GetAllUpgrades() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 594
   at EditPlayerData.UI.TowerPlayerDataSetting.GetValue() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 604
   at EditPlayerData.UI.PlayerDataSetting.GetValueDisplay() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 95
   at EditPlayerData.UI.PlayerDataSettingDisplay.SetSetting(PlayerDataSetting setting) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSettingDisplay.cs:line 71
   at EditPlayerData.UI.EditPlayerDataMenu.UpdateVisibleEntries() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 326
   at EditPlayerData.UI.EditPlayerDataMenu.SetPage(Int32 page) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 345
   at EditPlayerData.UI.EditPlayerDataMenu.<OnMenuOpened>b__12_4(Int32 i) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 250
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]_System.Int32(IntPtr , Int32 , Il2CppMethodInfo* )

**Comment by MaliciousFiles** [comment]
I can't reproduce this. Try downloading the newest version of the mod when it comes out in the next day or two.
