### ISSUE TITLE
No option to edit the quantity of my instamonkeys.

### ISSUE THREAD

**Issue by Wario3493** [MaliciousFiles/EditPlayerData#7]
<img width="960" alt="3Q" src="https://github.com/MaliciousFiles/EditPlayerData/assets/130720837/68630ec8-a3d2-41fc-8110-a29c259d99db">

**Comment by MaliciousFiles** [comment]
I'm confused as to the problem here. Do you not see instamonkeys in the dropdown to the top left? Try scrolling in that dropdown as well, I don't recall if you need to sometimes or not.

**Comment by Wario3493** [comment]
No. There's nothing there to edit my instas. I have 50 of all 1,472 instas in the game and I'm trying to decrease it, only repeats of other settings

**Comment by MaliciousFiles** [comment]
Interesting. Screenshots of the dropdown would be helpful, in addition to output from the MelonLoader log. I likely won't be able to test stuff on my end for a couple of days (I have some exams coming up), but I'll try to recreate after that.

**Comment by Wario3493** [comment]
[01:03:02.572] ------------------------------
[01:03:02.630] MelonLoader v0.6.2 Open-Beta
[01:03:02.632] OS: Windows 10
[01:03:02.632] Hash Code: 2AD1478D8329B7784C949251EAF68C4C50E2FE9DA6CBB4BDF1DCD43E9026C63C
[01:03:02.632] ------------------------------
[01:03:02.633] Game Type: Il2cpp
[01:03:02.633] Game Arch: x64
[01:03:02.633] ------------------------------
[01:03:02.634] Core::BasePath = C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6
[01:03:02.634] Game::BasePath = C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6
[01:03:02.634] Game::DataPath = C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\BloonsTD6_Data
[01:03:02.634] Game::ApplicationPath = C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\BloonsTD6.exe
[01:03:02.635] Runtime Type: net6
[01:03:02.781] ------------------------------
[01:03:02.782] Game Name: BloonsTD6
[01:03:02.782] Game Developer: Ninja Kiwi
[01:03:02.784] Unity Version: 2022.3.7f1
[01:03:02.784] Game Version: 40.2
[01:03:02.785] ------------------------------

[01:03:03.601] Preferences Loaded!

[01:03:04.044] Loading UserLibss from 'C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\UserLibs'...

[01:03:04.060] Loading Plugins from 'C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\Plugins'...
[01:03:04.062] 0 Plugins loaded.
[01:03:04.931] Loading Il2CppAssemblyGenerator...
[01:03:04.980] [Il2CppAssemblyGenerator] Contacting RemoteAPI...
[01:03:05.520] [Il2CppAssemblyGenerator] RemoteAPI.DumperVersion = null
[01:03:05.521] [Il2CppAssemblyGenerator] RemoteAPI.ObfuscationRegex = null
[01:03:05.523] [Il2CppAssemblyGenerator] RemoteAPI.MappingURL = null
[01:03:05.523] [Il2CppAssemblyGenerator] RemoteAPI.MappingFileSHA512 = null
[01:03:05.543] [Il2CppAssemblyGenerator] Using Dumper Version: 2022.1.0-pre-release.13
[01:03:05.543] [Il2CppAssemblyGenerator] Using Il2CppInterop Version = 1.4.5
[01:03:05.544] [Il2CppAssemblyGenerator] Using Unity Dependencies Version = 2022.3.7
[01:03:05.545] [Il2CppAssemblyGenerator] Using Deobfuscation Regex = null
[01:03:05.549] [Il2CppAssemblyGenerator] Cpp2IL is up to date.
[01:03:05.549] [Il2CppAssemblyGenerator] UnityDependencies is up to date.
[01:03:05.550] [Il2CppAssemblyGenerator] Checking GameAssembly...
[01:03:05.851] [Il2CppAssemblyGenerator] Assembly is up to date. No Generation Needed.

[01:03:05.855] Loading Mods from 'C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\Mods'...
[01:03:05.858] ------------------------------
[01:03:05.870] Melon Assembly loaded: '.\Mods\BTD6Cobra.dll'
[01:03:05.871] SHA256 Hash: 'f66887e7f5475935a3e81f5f38639c387ef9e67da7cd65f6b0e0ec9b03cbaac8'
[01:03:05.952] Melon Assembly loaded: '.\Mods\Btd6ModHelper.dll'
[01:03:05.952] SHA256 Hash: '016baee26e09e1ac3a983242289fd70574285528e652cfaecabea59097cc7c85'
[01:03:06.181] Melon Assembly loaded: '.\Mods\DJDTowerPack.dll'
[01:03:06.181] SHA256 Hash: '582bdaf9c687306a97d146f54e9f17f5ea027eb7d720dd8751b412dd60903799'
[01:03:06.208] Melon Assembly loaded: '.\Mods\EditPlayerData.dll'
[01:03:06.208] SHA256 Hash: '391e86c856600a428953a22d7bcdd33c0dc36f60e5ef01efb3094890e326b6c8'
[01:03:06.212] Melon Assembly loaded: '.\Mods\Multicash.dll'
[01:03:06.213] SHA256 Hash: '47f303ca1730c9b1bce021769ccd6715da229ebe297b90bf18065495f58efffe'

[01:03:06.869] ------------------------------
[01:03:06.870] BloonsTD6 Mod Helper v3.1.16
[01:03:06.870] by Gurrenm4 and Doombubbles
[01:03:06.872] Assembly: Btd6ModHelper.dll
[01:03:06.872] ------------------------------
[01:03:06.877] ------------------------------
[01:03:06.878] COBRA v1.0.0
[01:03:06.878] by bennik06
[01:03:06.879] Assembly: BTD6Cobra.dll
[01:03:06.879] ------------------------------
[01:03:06.886] ------------------------------
[01:03:06.887] DJDTowerPack v1.1.0
[01:03:06.887] by DatJaneDoe
[01:03:06.888] Assembly: DJDTowerPack.dll
[01:03:06.888] ------------------------------
[01:03:06.895] ------------------------------
[01:03:06.897] EditPlayerData v1.0.0
[01:03:06.897] by MaliciousFiles
[01:03:06.898] Assembly: EditPlayerData.dll
[01:03:06.899] ------------------------------
[01:03:06.905] ------------------------------
[01:03:06.905] MultiCash v1.0.5
[01:03:06.906] by Felixfex
[01:03:06.906] Assembly: Multicash.dll
[01:03:06.907] ------------------------------
[01:03:06.908] ------------------------------
[01:03:06.908] 5 Mods loaded.

[01:03:07.629] Class::Init signatures have been exhausted, using a substitute!
[01:03:07.677] Registered mono type Il2CppInterop.Runtime.DelegateSupport+Il2CppToMonoDelegateReference in il2cpp domain
[01:03:07.747] Registered mono type MelonLoader.Support.MonoEnumeratorWrapper in il2cpp domain
[01:03:07.749] Registered mono type MelonLoader.Support.SM_Component in il2cpp domain
[01:03:07.763] Support Module Loaded: C:\Program Files (x86)\Steam\New folder\steamapps\common\BloonsTD6\MelonLoader\Dependencies\SupportModules\Il2Cpp.dll
[01:03:07.907] Method Void SetNumColumns(Int32, Int32[]) on type EditPlayerData.UI.ModHelperTable has unsupported parameter Int32[] colFlex of type System.Int32[]
[01:03:07.914] Method Void SetSetting(EditPlayerData.UI.PlayerDataSetting) on type EditPlayerData.UI.PlayerDataSettingDisplay has unsupported parameter EditPlayerData.UI.PlayerDataSetting setting of type EditPlayerData.UI.PlayerDataSetting
[01:03:09.314] [BloonsTD6_Mod_Helper] Failed to get modders data
[01:03:09.325] [BloonsTD6_Mod_Helper] System.Net.Http.HttpRequestException: No such host is known. (raw.githubusercontent.com:443)
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at BTD_Mod_Helper.Api.Internal.ModHelperGithub.GetVerifiedModders()
[01:03:09.564] [DJDTowerPack] DJD Tower Pack
[01:03:09.579] [EditPlayerData] EditPlayerData loaded!
[01:03:09.595] [MultiCash] Multicash loaded!
[01:03:35.448] [BloonsTD6_Mod_Helper] Registering ModContent for BloonsTD6 Mod Helper...
[01:03:35.450] [BloonsTD6_Mod_Helper] Registering ModContent for COBRA...
[01:03:35.578] [BloonsTD6_Mod_Helper] Registering ModContent for DJDTowerPack...
[01:03:36.855] [BloonsTD6_Mod_Helper] Registering ModContent for EditPlayerData...
[01:05:42.483] Preferences Saved!

**Comment by MaliciousFiles** [comment]
If this is still an issue on the new version coming out in a couple days, feel free to open another issue.
