### ISSUE TITLE
the "towers" tab doesnt work in v41

### ISSUE THREAD

**Issue by GlooGunner** [MaliciousFiles/EditPlayerData#8]

**Comment by GlooGunner** [comment]
![image_2024-02-10_112928979](https://github.com/MaliciousFiles/EditPlayerData/assets/100978771/2db87401-a067-452a-a0ba-1eaf417cc53d)
it just shows the previous tab along with the very first monkey

**Comment by MaliciousFiles** [comment]
Looks like there's an error in the rendering. Could you send the MelonLoader console log?

**Comment by tapoffers** [comment]
[20:58:37.672] Exception in IL2CPP-to-Managed trampoline, not passing it to il2cpp: Il2CppInterop.Runtime.Il2CppException: System.NullReferenceException: Object reference not set to an instance of an object.
--- BEGIN IL2CPP STACK TRACE ---
System.NullReferenceException: Object reference not set to an instance of an object.
  at Assets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId (System.String baseId) [0x00000] in <00000000000000000000000000000000>:0
--- END IL2CPP STACK TRACE ---

   at Il2CppInterop.Runtime.Il2CppException.RaiseExceptionIfNecessary(IntPtr returnedException) in /home/runner/work/Il2CppInterop/Il2CppInterop/Il2CppInterop.Runtime/Il2CppException.cs:line 36
   at Il2CppAssets.Scripts.Models.GameModel.GetParagonUpgradeForTowerId(String baseId)
   at EditPlayerData.UI.TowerPlayerDataSetting.GetAllUpgrades() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 593
   at EditPlayerData.UI.TowerPlayerDataSetting.GetValue() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 603
   at EditPlayerData.UI.PlayerDataSetting.GetValueDisplay() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSetting.cs:line 94
   at EditPlayerData.UI.PlayerDataSettingDisplay.SetSetting(PlayerDataSetting setting) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/UI/PlayerDataSettingDisplay.cs:line 71
   at EditPlayerData.UI.EditPlayerDataMenu.UpdateVisibleEntries() in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 307
   at EditPlayerData.UI.EditPlayerDataMenu.SetPage(Int32 page) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 326
   at EditPlayerData.UI.EditPlayerDataMenu.<OnMenuOpened>b__12_4(Int32 i) in /home/runner/work/EditPlayerData/EditPlayerData/EditPlayerData/EditPlayerDataMenu.cs:line 231
   at (il2cpp delegate trampoline) System.Void_System.Action`1[[System.Int32, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]_System.Int32(IntPtr , Int32 , Il2CppMethodInfo* )

**Comment by MaliciousFiles** [comment]
Ah ok, looks like NK changed the backend again. I'll try to look into it this weekend. Hopefully it'll just be a small adjustment like last time.

**Comment by MaliciousFiles** [comment]
Should be fixed within a couple days!
